FiaStore/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('venta.urls', namespace='venta')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

venta/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import #importamos ambas lineas para que no se generen errores

from django.conf.urls import url, handler404
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.contrib import admin

#from django.conf.urls import handler404
#import django.views.defaults 

app_name = 'venta'
admin.autodiscover()


urlpatterns = [
    url(r'^login/$', views.auth_login,name="authentication"),
    url(r'^registrarse/$', views.auth_signup,name="authentication"),
    url(r'^logout/$',auth_views.logout, {'next_page':'/'}, name='logout'),
    url(r'^$', views.index),
	url(r'^perfil/', views.perfil,name='perfil'),
    url(r'^mensajes/', views.ver_mensajes),
    url(r'^misventas/', views.misventas),
    url(r'^eliminarUtilidad/', views.eliminarUtilidad),
    url(r'^(?P<producto_id>[0-9]+)/producto/$', views.ver_producto, name="producto"), 
    url(r'^(?P<perfil_id>[0-9]+)/ver_perfil/$',views.ver_perfil, name='ver_perfil'),
    url(r'^(?P<perfil_id>[0-9]+)/editar$',views.editar, name='editar'),
    url(r'^(?P<perfil_id>[0-9]+)/editar_foto/$',views.editar_foto, name='editar_foto'),
    url(r'^(?P<user_id>[0-9]+)/editar_contra/$',views.editar_contra, name='editar_contra'),
    url(r'^(?P<envio_id>[0-9]+)/message/$',views.mensaje_envio, name='message'),    
    url(r'^(?P<prod_id>[0-9]+)/comentario/$',views.comentario_producto, name='comentario'),
    url(r'^(?P<venta_id>[0-9]+)/eliminar/$',views.eliminarVenta, name='eliminar'),
    url(r'^(?P<user_id>[0-9]+)/eliminarUsuario/$',views.EliminarUsuario, name='eliminarUsuario'),
    url(r'^reporte/$', views.reporte),
	url(r'^nuevoProducto/', views.nuevoProducto),
]

venta/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class Vendedor(models.Model):
	carnet = models.CharField(max_length=7)
	nombre = models.CharField(max_length=50)
	apellido = models.CharField(max_length=50)
	telefono = models.CharField(max_length=10,blank=True)
	email = models.CharField(max_length=50, blank=True)
	password = models.CharField(max_length=10)
	image = models.ImageField(blank=True)
	genero = models.CharField(max_length=10, blank=True)
	user = models.ForeignKey(settings.AUTH_USER_MODEL)


class Producto(models.Model):
	nombre = models.CharField(max_length=100)
	precio = models.DecimalField(max_digits=6, decimal_places=2)
	fecha = models.DateField()
	descripcion=  models.CharField(max_length=100)
	image = models.ImageField(blank=False)
	tipo = models.CharField(max_length=17)
	vendedor = models.ForeignKey(settings.AUTH_USER_MODEL)

	def __str__(self):
		return self.nombre

class comentarioProducto(models.Model):
	texto = models.CharField(max_length=100)
	emisor = models.CharField(max_length=50)
	producto = models.ForeignKey(Producto,on_delete=models.CASCADE)

class mensaje(models.Model):
	texto = models.CharField(max_length=100)
	emisor = models.CharField(max_length=50)
	usuario = models.ForeignKey(settings.AUTH_USER_MODEL)


class Utilidad(models.Model):
	nombre = models.CharField(max_length=100)
	saldo = models.DecimalField(max_digits=10, decimal_places=2)
	concepto = models.CharField(max_length=150)
	fecha = models.DateField()
	user = models.ForeignKey(settings.AUTH_USER_MODEL)


class ReportarUsuario(models.Model):
	numeroReport = models.IntegerField(default=0,blank=True)
	usuarioReportado = models.ForeignKey(settings.AUTH_USER_MODEL)
	

class TipoReporte(models.Model):
	usuarioReportador = models.ForeignKey(settings.AUTH_USER_MODEL)
	tipo = models.CharField(max_length=200)
	reportes = models.ForeignKey(ReportarUsuario,on_delete=models.CASCADE)

venta/views.py
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from django.shortcuts import render, get_object_or_404, redirect
from django.shortcuts import render_to_response
from django.http import HttpResponse
from django.template import loader, RequestContext
from django.http.response import HttpResponseRedirect, HttpResponse
from django.views import generic
from django.views.defaults import page_not_found
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.db.models import Sum
from datetime import time, date
from .models import *
from .reporte import generar_reporte
from django.db.models import Q
from .inicializar import *
from django.contrib.staticfiles import  *
#metodo para logearse
def auth_login(request):
	if request.method == 'POST':
		username = request.POST.get('username',None)
		password = request.POST.get('password', None)
		user = authenticate(username=username, password=password)
	 	if user:
			login(request,user)
			return redirect('/')
		else :
			valor = "Volver a escribir credenciales."
			context= { 'valor':valor }
			return render(request,'Main/login.html',context)

	context= {}
	return render(request,'Main/login.html',context)

#metodo para registrarse
def auth_signup(request):
	newUser = Vendedor()
	if request.method == 'POST':
		username = request.POST.get('username',None)
		password = request.POST.get('password', None)
		password2 = request.POST.get('password2', None)
		email=request.POST.get('email',None)
		user = authenticate(username=username, password=password, password2=password2)
		
		if user :
		 	valor = "Ese usuario ya esta registrado, seleccione otro"
			context= { 'valor':valor }
			return render(request,'Main/registrar.html',context)
		if password==password2:
			newUser.carnet = username
			newUser.password = request.POST.get('password',None)
			newUser.password2 = request.POST.get('password2',None)
			newUser.nombre = request.POST.get('nombre',None)
			newUser.apellido =request.POST.get('apellido',None)
			genero = request.POST.get('genero',None)
			newUser.image= request.FILES.get('imagen',None)
			newUser.genero=genero

			newUser.telefono= request.POST.get('telefono',None)
			newUser.email=request.POST.get('email',None)
			user = User.objects.create_user(username=username,email=email, password= password)
		 	user.save()
		 	report = ReportarUsuario()
		 	report.usuarioReportado=user
		 	report.save()
		 	newUser.user=user
			newUser.save()
		 	login(request,user)
		 	return redirect('/')
		else :
			valor1 = "Las contrasenias son diferentes"
			context= { 'valor1':valor1 }
			return render(request,'Main/registrar.html',context) 	
	context= {}
	return render(request,'Main/registrar.html',context)
	
"""def mi_error_404(request):
    nombre_template = '404.html'
    return page_not_found(request, template_name=nombre_template)
 """

def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('500.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response


def index(request):
	product = Producto.objects.order_by('fecha') #todos los productos
	electronico=Producto.objects.filter(tipo__contains='electronico').order_by('fecha')
	material=Producto.objects.filter(tipo__contains='material').order_by('fecha')
	libros =Producto.objects.filter(tipo__contains='libros').order_by('fecha')
	otros=Producto.objects.filter(tipo__contains='otros').order_by('fecha')
	template = loader.get_template('Main/index.html')
	todos = User.objects.all()
	usuarios = User.objects.exclude(username__contains='fiaOferta2017')
	superuser = User.objects.filter(username__contains='fiaOferta2017')
	iniciarSuperUser()
	i = len(product)

	context = {
		'i':i,
		'todos':todos,
		'usuarios':usuarios,
		'superuser':superuser,
		'electronico':electronico,
		'material':material,
		'libros':libros,
		'otros':otros,
		'product':product,
	}
	if request.method=='POST':
		action=request.POST.get('action',None)
		if action =='buscar':
			nombre = request.POST.get('buscar',None)
			context=buscar(nombre)
			return HttpResponse(template.render(context,request) )
	return HttpResponse(template.render(context, request))


def superUsuario(request):
	template=loader.get_template('Main/index.html')
	context = 'Estas como super usuario'
	return HttpResponse(template.render(context,request))

def buscar(nombre):
	producto = Producto.objects.filter(nombre__contains=nombre).order_by('fecha')
	i = len(producto)
	context ={'otros':producto,'i':i, 'busqueda':'busqueda'}
	return context

def reporte(request):
	usuario=request.user
	return generar_reporte(request, usuario)


def ver_producto(request,  producto_id):
	producto = get_object_or_404(Producto, pk= producto_id)
	try:
		nomb = request.user
		context={'producto':producto,'nomb':nomb}
		return render(request,'Main/producto.html',context)

	except (KeyError, producto.DoesNotExist):
		return render(request, '404.html', {
		    	'error_message': "Tiene que seleccionar una respuesta",
		})
	else:
		return redirect('/')


def perfil(request):
	template = loader.get_template('Main/perfil.html')
	return HttpResponse(template.render({}, request))


def ver_mensajes(request):
	template = loader.get_template('Main/mensajes.html')
	return HttpResponse(template.render({}, request))

def misventas(request):
	template = loader.get_template('Main/misventas.html')
	utilidad = 0;

	usuario = request.user
		#utilidad = Utilidad.objects.aggregate(Sum('saldo'))
	for ut in request.user.utilidad_set.all() :
		utilidad = utilidad + ut.saldo

	return HttpResponse(template.render({'utilidad':utilidad}, request))	
	

def ver_perfil(request, perfil_id):
	perfil = get_object_or_404(User, pk= perfil_id)
	usuario = request.user
	try:
		if request.method=='POST':
			try:
				tipo = TipoReporte.objects.get(usuarioReportador=usuario)
				reportes = ReportarUsuario.objects.filter(usuarioReportado=perfil)
				context = {'perfil':perfil,'usuario':usuario,'reportes':reportes,'valor':'ya antes ha reportado a este usuario'}
				return render(request,'Main/ver_perfil.html',context)
			except (KeyError, TipoReporte.DoesNotExist):
				reporte = ReportarUsuario.objects.get(usuarioReportado=perfil)
				tipo = TipoReporte()
				tipo.tipo=request.POST.get('dato',None)
				tipo.usuarioReportador=usuario
				reporte.numeroReport = reporte.numeroReport+1
				reporte.save()
				tipo.reportes=reporte
				tipo.save()
		
		reportes = ReportarUsuario.objects.filter(usuarioReportado=perfil)
		context = {'perfil':perfil,'usuario':usuario,'reportes':reportes,}
		return render(request,'Main/ver_perfil.html',context)
		
	except (KeyError, perfil.DoesNotExist):
		return render(request, 'Main/404.html', {
		    	'error_message': "Tiene que seleccionar una respuesta",
		})
	else:
		return redirect('/')

def eliminarUtilidad(request):
	usuario = request.user
	try:
		for ut in usuario.utilidad_set.all() :
			ut.delete()
		return render_to_response('Main/index.html',{'mensaje':'objeto eliminado con exito'})
	except (KeyError, venta.DoesNotExist):
		return render(request, 'Main/404.html', {
		    	'error_message': "No selecciono una venta valida a eliminar",
		})
	else:
		return redirect('/')

def EliminarUsuario(request,user_id):
	usuarioE = get_object_or_404(User,pk= user_id)
	try:
		template = loader.get_template('Main/index.html')
		usuario= request.user
		usuarioE.delete()
		context={}
		login(request,usuario)
		return redirect('/')
	except (KeyError, usuarioE.DoesNotExist):
		return render(request, 'Main/404.html', {
		    	'error_message': "No selecciono una venta valida a eliminar",
		})
	else:
		return redirect('/')

def editar(request, perfil_id):
	perfil = get_object_or_404(Vendedor, pk= perfil_id)
	try:
		if request.method == 'POST' :
			email = request.POST.get('email','SM') #SM = Sin Modificacion
			cel = request.POST.get('telefono','SM')
			perfil.telefono = cel
			perfil.email= email
			newId = request.POST.get('newid','SM')
			perfil.save()
			context={'email':email, 'cel':cel, 'perfil':perfil, perfil_id:'perfil_id', 'newid':newId}

			#return render_to_response('Main/Perfil.html',context)
			return redirect('venta:perfil')	
		else :
			context={'perfil':perfil}
			return render_to_response('Main/editarPerfil.html',context)	

	except (KeyError, perfil.DoesNotExist):
		return render(request, 'Main/404.html', {
		    	'error_message': "Tiene que seleccionar",
		})
	else:
		return redirect('/')

def editar_foto(request, perfil_id):
	perfil = get_object_or_404(Vendedor, pk= perfil_id)
	try:
		if request.method == 'POST':
			foto = request.FILES.get('imagen','SM') #SM = Sin Modificacion
			perfil.image=foto
			perfil.save()
			context={perfil_id:'perfil_id', foto:'foto'}			
			#return render_to_response('Main/index.html',context)
			return redirect('venta:perfil')			
		else :
			context={'perfil':perfil}
			return render_to_response('Main/editar_foto.html',context)	

	except (KeyError, perfil.DoesNotExist):
		return render(request, 'Main/404.html', {
		    	'error_message': "Tiene que seleccionar",
		})
	else:
		return redirect('/')

def editar_contra(request, user_id):
	perfil = get_object_or_404(User, pk= user_id)
	try:
		if request.method == 'POST':
			password=request.POST.get('password', None)
			pas=check_password(password, perfil.password)
			if pas:
			
			    contra = request.POST.get('contra',None) 
			    info='Debe volver a iniciar sesion'
			    perfil.set_password(contra)
			    perfil.save()
			    login(request,perfil)#esto es xq al guardar otra contrasena cierra sesion
			    #update_session_auth_hash(request,perfil) #tambien se puede usar 
			    info='Debe volver a iniciar sesion'

venta/templates/Main/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title> {% block titulo %} {% endblock %} </title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static "imagenes/fiaOfertasLogo.png" %}" />
	<meta charset="utf-8">
	<meta name="author" content="FIAofertas">
    <meta name="Title" content="FIAofertas"/>
    <meta name="keywords" content="FIAofertas, tienda, fiaofertas, online, venta, ofertas, chart.js"> 
    <meta name="Description" content="Realiza tus compras y ventas de articulos de manera rapida y sencilla en la FIA"/>
    
    <meta name="robots" content="index">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="{% static "css/baseFIAofertas.css" %}"/>
	<link rel="stylesheet" href="{% static "css/edicionHistorial.css" %}"/>
	<link rel="stylesheet" href="{% static "css/edicionForo.css" %}"/>

	<style>
		@font-face{
			font-family: "Lobster-Regular";
			src: url('{% static 'fonts/Lobster-Regular.ttf' %}') format("truetype");
		}

		@font-face{
			font-family: "Righteous-Regular";
			src: url("{% static 'fonts/Righteous-Regular.ttf'%}") format("truetype");
		}

    	{% if user.is_authenticated %}
				body{
				    background: url('{% static 'imagenes/fondo.jpg' %}');
				    background-repeat: no-repeat;
				    background-size: cover;
				    background-attachment: fixed;
				}
    	{% else %}

    			.container{
		    		margin: 20px 100px 100px 100px;
		    	}
    			body{
				    background: url('{% static 'imagenes/fondoLogIn.jpg' %}');
				    background-repeat: no-repeat;
				    background-size: cover;
				    background-attachment: fixed;
				}
    	{% endif %}
	</style>

</head>
<body>
{% if user.is_superuser %}
<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
		    <div class="navbar-header">
		      <a class="navbar-brand" href="/">FiaOfertas</a>
		    </div>
		    <div class="collapse navbar-collapse" id="myNavbar">
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="/logout">Salir</a></li>
		      </ul>
		    </div>
		</div>
	</nav>


	<section class="container">


        {% if todos %}
        	<h1 id="usuarios">Usuarios</h1>

        		{% for u in superuser %}
        			<center><h3 style="font-family: 'Righteous-Regular',cursive;"><strong>Superusuario:</strong> {{u.username}}</h3></center>	
        		{% endfor%}
        		<center><img src="{% static "imagenes/fiaOfertasLogo.png" %}" alt="no se puede mostrar imagen" class="img-rounded img-responsive image" width="300px" height="300px" /></center>	

			<table class="table table-bordered table-hover table-responsive">
				<thead>
					 <tr>
				        <th>Carnet</th>
				        <th>Nombre</th>			        
				        <th>Apellido</th>
				        <th>Género</th>
				        <th>Cant. de veces reportado</th>
				        <th>Eliminar</th>
				        <th>Mensaje</th>
				    </tr>
					</thead>
				<tbody>
					{% for pr in usuarios %}
						<tr>
							<th>{{pr.username}}</th>
						{% for es in pr.vendedor_set.all %}
					        <th>{{es.nombre}}</th>
					        <th>{{es.apellido}}</th>			        
					        <th>{{es.genero}}</th>
				    	{% endfor %}
				    	{% for re in pr.reportarusuario_set.all %}    
				        	<th>{{re.numeroReport}}</th>
				        	<th><button class="btn" onclick="location='{% url 'venta:eliminarUsuario' pr.id %}'">Eliminar</button></th>
				        	{% if re.numeroReport > 10 %}
				        		<th>Se recomienda elimar usuario</th>
				        	{% else %}
				        		<th>No hay necesidad de borrar este usuario</th>
				        	{% endif %}
				        {% endfor %}
				    </tr>
				    {% endfor %}
				</tbody>
			</table>

		{% endif %} 

 	
{% else %}   	
{% if user.is_authenticated %}
	{% for vendedor in user.vendedor_set.all %}
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
		    <div class="navbar-header">
		      <a class="navbar-brand" href="/">FIAofertas</a>
		    </div>
		    <div class="collapse navbar-collapse" id="myNavbar">
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="/">Foro</a></li>
		        <li><a href="/perfil">Perfil</a></li>
		        <li><a href="/misventas">Mis Ventas</a></li>
		        <li><a href="/nuevoProducto">Nueva Venta</a></li>
		        <!--<li><a href="/login">Iniciar sesion</a></li>
		        <li><a href="/registrarse">Registrarse</a></li>-->
		        <li><a href="/logout">Salir</a></li>
		      </ul>
		    </div>
		</div>
	</nav>
{% endfor %}
{% else %}
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
		    <div class="navbar-header">
		      <a class="navbar-brand" href="/">FIAofertas</a>
		    </div>
		    <div class="collapse navbar-collapse" id="myNavbar">
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="/">Foro</a></li>
		        <li><a href="/perfil">Perfil</a></li>
		        <li><a href="/login">LogIn</a></li>
		        <li><a href="/registrarse">Registrarse</a></li>
		      </ul>
		    </div>
		</div>
	</nav>
	<div class="alert alert-warning">
   		<strong>¡No ha iniciado sesión!</strong> Inicie Sesión: <a href="/login">Log In</a>
	</div>

{% endif %}

	<section class="container">

		<h1>Foro de productos</h1>

		<div class="col-sm-4 col-md-4">
			<img src="{% static "imagenes/fiaOfertasLogo.png" %}" alt="" class="img-rounded img-responsive" height="300px" width="300px" />
			<center> <p> <strong>Nº de ventas:</strong> <input type="text" disabled="true" value="{{i}}" size="3px"> </p> </center>
			<br />
            <div class="dropdown">
			    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Categorías
			    <span class="caret"></span></button>
			    <ul class="dropdown-menu">
			      <li><a href="#libros" class="ancla">Libros</a></li>
			      <li><a href="#electrónico" class="ancla">Electrónico</a></li>
			      <li><a href="#materiales" class="ancla">Materiales</a></li>
			      <li><a href="#otros" class="ancla">Otros</a></li>
			    </ul>
			</div>
			<br />
		   <form action="" method="POST">
				<div class="form-group form-inline">
					{% csrf_token %}
					<label>Buscar:</label>
					<input type="hidden" name="action" id="action" value="buscar">
					<input type="text" name="buscar" id="buscar" class="form-control">
					<input type="submit" class="btn" name="btbuscar" id="btbuscar">
				</div>
			</form>
        </div>

        <div class="col-sm-8 col-md-8 content">

        	{% if libros %}
        	<h2 id="libros">Libros</h2>
        		{% for pr in libros %}					
				    <p><strong>ID:</strong> {{pr.id}}</p>
					<p><strong>Descripción: </strong>{{pr.nombre}}</p>
					<p><strong>Fecha: </strong>{{pr.fecha}}</p>
					<p><strong>Precio: </strong>${{pr.precio}}</p>
					<p><button class="btn" onclick = "location='{% url 'venta:producto' pr.id %}'"/>Ver Venta</button></p>
					<hr />
				{% endfor %}
			{% endif %} 

			{% if electronico %}
				<h2 id="electronico">Electrónico</h2>
				{% for pr in electronico %}
				    <p><strong>ID:</strong> {{pr.id}}</p>
					<p><strong>Descripción: </strong>{{pr.nombre}}</p>
					<p><strong>Fecha: </strong>{{pr.fecha}}</p>
					<p><strong>Precio: </strong>${{pr.precio}}</p>
					<p><button class="btn" onclick = "location='{% url 'venta:producto' pr.id %}'"/>Ver Venta</button></p>
					<hr />
				{% endfor %}
			{% endif %} 

			{% if material %}
				<h2 id="materiales">Materiales</h2>
				{% for pr in material %}
				    <p><strong>ID:</strong> {{pr.id}}</p>
					<p><strong>Descripción: </strong>{{pr.nombre}}</p>
					<p><strong>Fecha: </strong>{{pr.fecha}}</p>
					<p><strong>Precio: </strong>${{pr.precio}}</p>
					<p><button class="btn" onclick = "location='{% url 'venta:producto' pr.id %}'"/>Ver Venta</button></p>
					<hr />
				{% endfor %}
			{% endif %} 

			{% if otros %}
				<h2 id="otros">Otros</h2>
				{% for pr in otros %}
				    <p><strong>ID:</strong> {{pr.id}}</p>
					<p><strong>Descripción: </strong>{{pr.nombre}}</p>
					<p><strong>Fecha: </strong>{{pr.fecha}}</p>
					<p><strong>Precio: </strong>${{pr.precio}}</p>
					<p><button class="btn" onclick = "location='{% url 'venta:producto' pr.id %}'"/>Ver Venta</button></p>
					<hr />
				{% endfor %}
			{% endif %} 					
		</div>

		{% if user.is_authenticated %}
			<br>
			<center><submit class="btn" onclick = "location='/nuevoProducto'"/>Realizar venta <i class="glyphicon glyphicon-check"></i></submit></center>
		{% endif %}

		<!--
		<div class="table-responsive container-table">
		{% if electronico %}
			<table class="table table-hover">
			    <thead>
			    <tr> <h2>Electronico</h2> </tr>
			     <tr>
			        <th>id</th>
			        <th>Venta ofertada</th>
			        <th>Fecha</th>
			        <th>precio</th>
			        <th>Opciones</th>
			      </tr>
			    </thead>
			    <tbody>
			    {% for pr in electronico %}
			    	<tr>
			        	<td> {{pr.id}} </td>
			        	<td> {{pr.nombre}} </td>
			        	<td> {{pr.fecha}} </td>
			        	<td> ${{pr.precio}} </td>
			        	<td>
			        		<a href="{% url 'venta:producto' pr.id %}">ver</a>
			        	</td>
			      	</tr>
			     {% endfor %}
			      </tbody>
			</table>
		{% endif %}
		</div>
		<div class="table-responsive container-table">
			<table class="table table-hover">
			{% if material %}
			    <thead>
			    <tr> <h2>Materiales</h2> </tr>
			     <tr>
			        <th>id</th>
			        <th>Venta ofertada</th>
			        <th>Fecha</th>
			        <th>precio</th>
			        <th>Opciones</th>
			      </tr>
			    </thead>
			    <tbody>
			    {% for pr in material %}
			    	<tr>
			        	<td> {{pr.id}} </td>
			        	<td> {{pr.nombre}} </td>
			        	<td> {{pr.fecha}} </td>
			        	<td> ${{pr.precio}} </td>
			        	<td>
			        		<a href="{% url 'venta:producto' pr.id %}">ver</a>
			        	</td>
			      	</tr>
			     {% endfor %}
			      </tbody>
			</table>
		{% endif %}
		</div>
		<div class="table-responsive container-table">
		{% if libros %}
			<table class="table table-hover">
			    <thead>
			    <tr> <h2>Libros</h2> </tr>
			     <tr>
			        <th>id</th>
			        <th>Venta ofertada</th>
			        <th>Fecha</th>
			        <th>precio</th>
			        <th>Opciones</th>
			      </tr>
			    </thead>
			    <tbody>
			    {% for pr in libros %}
			    	<tr>
			        	<td> {{pr.id}} </td>
			        	<td> {{pr.nombre}} </td>
			        	<td> {{pr.fecha}} </td>
			        	<td> ${{pr.precio}} </td>
			        	<td>
			        		<a href="{% url 'venta:producto' pr.id %}">ver</a>
			        	</td>
			      	</tr>
			     {% endfor %}
			      </tbody>
			</table>
		{% endif %}
		</div>
		<div class="table-responsive container-table">
		{% if otros %}
			<table class="table table-hover">
			    <thead>
			    <tr> <h2> Otros </h2> </tr>
			     <tr>
			        <th>id</th>
			        <th>Venta ofertada</th>
			        <th>Fecha</th>
			        <th>precio</th>
			        <th>Opciones</th>
			      </tr>
			    </thead>
			    <tbody>
			    {% for pr in otros %}
			    	<tr>
			        	<td> {{pr.id}} </td>
			        	<td> {{pr.nombre}} </td>
			        	<td> {{pr.fecha}} </td>
			        	<td> ${{pr.precio}} </td>
			        	<td>
			        		<a href="{% url 'venta:producto' pr.id %}">ver</a>
			        	</td>
			      	</tr>
			     {% endfor %}
			      </tbody>
			</table>
		{% endif %}
		</div>-->
	</section>
</body>
</html>
{% endif %}